<?php
//multi-select,select,text,checkbox,number

$media_music_books = [
	[
        'Media, Music & Books',
        'child' => [  
          [
            'Books',
            'child'=>[
              [
                'Local Books',
                'child'=>[
                  ['Literature'],
                  ['Lifestyle Books'],
                  ['Teens Books'],
                  ['Biography Books'],
                  ['Business Books'],
                  ['Calendars'],
                  ['Babies Books'],
                  ['Toddlers Books'],
                  ['Parent\'s Books'],
                  ['Children\'s Books'],
                  ['Religion Books'],
                  ['Comic Books'],
                  ['Technology Books'],
                  ['Cooking Books'],
                  ['Pre Sell Books'],
                  ['Education Books'],
                  ['Fitness Books'],
                  ['History Books'],
                  ['Entertainment Books'],
                  ['Law Books'],
                  ['Photography Books'],
                  ['Medical Books'],
                  ['Thrillers'],
                  ['Relationship Books'],
                  ['Social Books'],
                  ['Professional Books'],
                  ['Romance'],
                  ['Science Books'],
                  ['Science Fiction Books'],
                  ['Self Help'],
                  ['Sport Books'],
                  ['Other Books'],
                  ['Travel Books'],
                  ['Art Books'],
                  ['Study Aids & Exam Preparations'],
                  ['Language, Linguistics & Writing'],
                  ['Text books'],
                ]
              ],
              [
                'English Books',
                'child'=>[
                  ['Lifestyle Books'],
                  ['Teens Books'],
                  ['Biography Books'],
                  ['Finance & Economics'],
                  ['Calendars'],
                  ['Babies Books'],
                  ['Toddlers\' Books'],
                  ['Parent\'s Books'],
                  ['Children\'s Books'],
                  ['Religion Books'],
                  ['Comic Books'],
                  ['Technology Books'],
                  ['Cooking Books'],
                  ['Pre Sell Books'],
                  ['Education Books'],
                  ['Fitness Books'],
                  ['History Books'],
                  ['Entertainment Books'],
                  ['Law Books'],
                  ['Art Books'],
                  ['Medical Books'],
                  ['Thrillers'],
                  ['Relationship Books'],
                  ['Social Books'],
                  ['Professional Books'],
                  ['Romance'],
                  ['Science Books'],
                  ['Science Fiction Books'],
                  ['Self Help'],
                  ['Literature'],
                  ['Travel Books'],
                  ['Business Books'],
                  ['Sport Books'],
                  ['Study Aids & Exam Preparations'],
                  [
                    'Language, Linguistics & Writing',
                    'child'=>[
                      ['Language Learning & Teaching'],
                      ['Linguistics'],
                      ['Grammar'],
                      ['Dictionaries'],
                    ]
                  ],
                  [
                    'Text books',
                    'child'=>[
                      ['High School']
                      ['University'],                    
                    ]
                  ],
                ]
              ],
              [
                'Chinese Books',
                'child'=>[
                  ['Literture'],
                  ['Lifestye Books'],
                  ['Teens Boks'],
                  ['Biogaphy Books'],
                  ['Busness Books'],
                  ['Caendars'],
                  ['Babis Books'],
                  ['Todders\' Books'],
                  ['Paren\'s Books'],
                  ['Childrn\'s Books'],
                  ['Religin Books'],
                  ['Comic ooks'],
                  ['Technolgy Books'],
                  ['CookingBooks'],
                  ['Pre Sel Books'],
                  ['Educatin Books'],
                  ['FitnessBooks'],
                  ['History ooks'],
                  ['Entertaiment Books'],
                  ['Law ooks'],
                  ['Art Boks'],
                  ['Medicl Books'],
                  ['Thrilers'],
                  ['Relaionship Books'],
                  ['Socal Books'],
                  ['Proessional Books'],
                  ['Rmance'],
                  ['Scienc Books'],
                  ['Scienc Fiction Books'],
                  ['Self elp'],
                  ['SportBooks'],
                  ['Travel ooks'],
                  ['Study Aid & Exam Preparations'],
                  [
                    'Language, Lnguistics & Writing',
                    'child'=>[
                      ['Language Learning & Teaching'],
                      ['Linguistics'],
                      ['Grammar'],
                      ['Dictionaries'],
                    ]
                  ],
                  [
                    'Text book',
                    'child'=>[
                      ['High School'],
                      ['University'],
                  ]
                  ],
                ]
              ],
              [
                'Calendars',
                'child'=>[
                  ['Wall calendars'],
                  ['Mini wall calendars'],
                  ['box calendars'],
                  ['planners'],
                ]
              ],
            ]
          ],
          [
            'eBooks',
            'child'=>[
              [
                'Local eBooks',
                'child'=>[
                  ['Literature'],
                  ['Lifestyle eBooks'],
                  ['Teens eBooks'],
                  ['Biography eBooks'],
                  ['Business eBooks'],
                  ['Calendars'],
                  ['Children\'s eBooks'],
                  ['Religion eBooks'],
                  ['Comic eBooks'],
                  ['Technology eBooks'],
                  ['Cooking eBooks'],
                  ['Pre Sell eBooks'],
                  ['Education eBooks'],
                  ['Fitness eBooks'],
                  ['History eBooks'],
                  ['Entertainment eBooks'],
                  ['Law eBooks'],
                  ['Art eBooks'],
                  ['Medical eBooks'],
                  ['Thrillers'],
                  ['Relationship eBooks'],
                  ['Social eBooks'],
                  ['Professional eBooks'],
                  ['Romance'],
                  ['Science eBooks'],
                  ['Science Fiction eBooks'],
                  ['Self Help'],
                  ['Sport eBooks'],
                  ['Travel eBooks'],
                ]
              ],
              [
                'English eBooks',
                'child'=>[
                  ['Literature'],
                  ['Lifestyle eBooks'],
                  ['Teens eBooks'],
                  ['Biography eBooks'],
                  ['Business eBooks'],
                  ['Calendars'],
                  ['Childrens eBooks'],
                  ['Religion eBooks'],
                  ['Comic eBooks'],
                  ['Technology eBooks'],
                  ['Cooking eBooks'],
                  ['Other eBooks'],
                  ['Education eBooks'],
                  ['Fitness eBooks'],
                  ['History eBooks'],
                  ['Entertainment eBooks'],
                  ['Law eBooks'],
                  ['Art eBooks'],
                  ['Medical eBooks'],
                  ['Thrillers'],
                  ['Relationship eBooks'],
                  ['Social eBooks'],
                  ['Professional eBooks'],
                  ['Romance'],
                  ['Science eBooks'],
                  ['Science Fiction eBooks'],
                  ['Self Help'],
                  ['Sport eBooks'],
                  ['Travel eBooks'],
                  ['Pre Sell eBooks'],
                ]
              ],
              [
                'Chinese eBooks',
                'child'=>[
                  ['Literature'],
                  ['Lifestyle eBooks'],
                  ['Teens eBooks'],
                  ['Biography eBooks'],
                  ['Business eBooks'],
                  ['Calendars'],
                  ['Children\'s eBooks'],
                  ['Religion eBooks'],
                  ['Comic eBooks'],
                  ['Technology eBooks'],
                  ['Cooking eBooks'],
                  ['Pre Sell eBooks'],
                  ['Education eBooks'],
                  ['Fitness eBooks'],
                  ['History eBooks'],
                  ['Entertainment eBooks'],
                  ['Law eBooks'],
                  ['Art eBooks'],
                  ['Medical eBooks'],
                  ['Thrillers'],
                  ['Relationship eBooks'],
                  ['Social eBooks'],
                  ['Professional eBooks'],
                  ['Romance'],
                  ['Science eBooks'],
                  ['Science Fiction eBooks'],
                  ['Self Help'],
                  ['Sport eBooks'],
                  ['Travel eBooks'],
                ]
              ],
            ]
          ],
          [
            'Magazines',
            'child'=>[
            ['Fashion Magazines'],
            ['Women\'s Lifestyle Magazines'],
            ['Men\'s Lifestyle Magazines'],
            ['Teen Magazines'],
            ['Health and Beauty Magazines'],
            ['Tourism Magazines'],
            ['Entertainment Magazines'],
            ['Life Magazines'],
            ['Home Deco Magazines'],
            ['Land and House Magazines'],
            ['Automotive Magazines'],
            ['Technology Magazines'],
            ['IT Magazines'],
            ['Design Magazines'],
            ['Mom and Babies Magazines'],
            ['Culinary Magazines'],
            ['Pets Magazines'],
            ['Films Magazines'],
            ['Music Magazines'],
            ['Knowledge Magazines'],
            ['Financial Magazines'],
            ['Education Magazines'],
            ['Nature Magazines'],
            ['Sports Magazines'],
            ['Jewelry Magazines'],
            ['Lifestyle Magazines'],
            ['Children Magazines'],
            ['TV Drama Magazines'],
            ['Gaming Magazines'],
            ['Food Magazines'],
            ]
          ],
          [
            'Movies',
            'child'=>[
              ['Action'],
              ['Comedy'],
              ['Drama'],
              ['Educational'],
              ['Horror'],
              ['Romance'],
              ['Romantic Comedy'],
              ['Box Sets'],
            ]
          ],
          [
            'TV Series',
            'child'=>[
              ['Action'],
              ['Comedy'],
              ['Drama'],
            ]
          ],
          [
            'Music',
            'child'=>[
              ['Children'],
              ['Inspirational'],
              ['OPM'],
              ['Rock'],
              ['Alternative Rock'],
              ['Blues'],
              ['Religion'],
              ['Classical'],
              ['Country'],
              ['Electronic'],
              ['Folk'],
              ['Gospel'],
              ['Metal & Hard Rock'],
              ['Local Music'],
              ['Jazz'],
              ['Celtic'],
              ['Opera'],
              ['Pop'],
              ['R&B'],
              ['Rap'],
              ['Hip-Hop'],
              ['Movie Soundtracks'],
              ['Reggae'],
            ]
          ],
          [
            'Musical Instruments',
            'child'=>[
              [
                'Pro & DJ Headphones',
                'child'=>[
                  ['DJ Headphones'],
                  ['Studio Headphones'],
                ]
              ],
              [
                'Guitars',
                'child'=>[
                  ['Electric Guitars'],
                  ['Acoustic Guitars'],
                  ['Acoustic-Electric Guitars'],
                  ['Amps'],
                  ['Effects Pedals'],
                  ['Guitar & Bass Accessories'],
                  ['Folk & World Strings'],
                  ['Ukulele'],
                  ['Premium Guitars'],
                ]
              ],
              [
                'Bass Guitars',
                'child'=>[
                  ['Electric Bass Guitars'],
                  ['Acoustic Bass Guitars'],
                  ['Bass Amplifiers'],
                   ]
              ],
              [
                'Woodwind',
                'child'=>[
                  ['Flute'],
                  ['Clarinet'],
                  ['Oboe'],
                ]
              ],
              [
                'Drums & Percussion',
                'child'=>[
                  ['Drum Sets'],
                  ['Electronic Drums'],
                  ['Drum Accessories'],
                  ['Cymbals'],
                  ['Folk & World Percussion'],
                ]
              ],
              [
                'Keyboards & Pianos',
                'child'=>[
                  ['Portable Keyboards'],
                  ['Digital Pianos'],
                  ['Synthesizers'],
                  ['MIDI Controllers'],
                  ['Folk & World Keyboards'],
                  ['Acoustic Pianos'],
                ]
              ],
              [
                'DJ, Karaoke & Electronic Music',
                'child'=>[
                  ['DJ Equipment'],
                  ['Karaoke'],
                  ['Lighting'],
                  ['Electronic Music'],
                ]
              ],
              [
                'Band & Orchestra',
                'child'=>[
                  ['Brass Instruments'],
                  ['Concert Percussion'],
                  ['Marching Percussion'],
                  ['Violins'],
                  ['Woodwinds'],
                  ['Brass Accessories'],
                  ['Woodwind Accessories'],
                  ['Orchestral Strings Accessories'],
                  ['Concert Percussion Accessories'],
                  ['Marching Percussion Accessories'],
                  ['Musical Fun for Kids'],
                ]
              ],
              [
                'Instrument Accessories',
                'child'=>[
                  ['Guitar & Bass Accessories'],
                  ['Drum & Percussion Accessories'],
                  ['Keyboard Accessories'],
                  ['Brass Accessories'],
                  ['Woodwind Accessories'],
                  ['Orchestral Strings Accessories'],
                  ['Concert Percussion Accessories'],
                  ['Marching Percussion Accessories'],
                  ['Folk & World Accessories'],
                  ['General Accessories'],
                ]
              ],
              ['Traditional instruments'],
              ['Others'],
            ]
          ],
        ]
     ], 
];
