<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.8.5
 */

/**
 * Database `bd_geo_code`
 */

/* `bd_geo_code`.`Municipals` */
$municipals = array(

    array('name' => 'Barisal City Corporation', 'ward'=> 30, 'bn_name' => 'বরিশাল সিটি কর্পোরেশন' , 'district_id' => '33'),
    array('name' => 'Chattogram City Corporatio', 'ward'=> 41, 'bn_name' => 'চট্টগ্রাম সিটি কর্পোরেশন' , 'district_id' => '8'),
    array('name' => 'Dhaka North City Corporation', 'ward'=> 54, 'bn_name' => 'ঢাকা উত্তর সিটি কর্পোরেশন' , 'district_id' => '47'),
    array('name' => 'Dhaka South City Corporation', 'ward'=> 75, 'bn_name' => 'ঢাকা দক্ষিণ সিটি কর্পোরেশন' , 'district_id' => '47'),
    array('name' => 'Khulna City Corporation', 'ward'=> 31, 'bn_name' => 'খুলনা সিটি কর্পোরেশন' , 'district_id' => '27'),
    array('name' => 'Rajshahi City Corporation', 'ward'=> 30, 'bn_name' => 'রাজশাহী সিটি কর্পোরেশন' , 'district_id' => '15'),
    array('name' => 'Sylhet City corporation', 'ward'=> 27, 'bn_name' => 'সিলেট সিটি কর্পোরেশন' , 'district_id' => '36'),
    array('name' => 'Comilla City Corporation', 'ward'=> 27, 'bn_name' => 'কুমিল্লা সিটি কর্পোরেশন' , 'district_id' => '1'),
    array('name' => 'Gazipur City Corporation', 'ward'=> 57, 'bn_name' => 'গাজীপুর সিটি কর্পোরেশন ' , 'district_id' => '41'),
    array('name' => 'Narayanganj City Corporation', 'ward'=> 27, 'bn_name' => 'নারায়ণগঞ্জ সিটি কর্পোরেশন' , 'district_id' => '43'),
    array('name' => 'Mymensingh City Corporation', 'ward'=> 33, 'bn_name' => 'ময়মনসিংহ সিটি কর্পোরেশন' , 'district_id' => '62'),
    

    array('name' => 'Amtali Paurashava','ward' => 9,'bn_name' => 'আমতলী', 'district_id' => '33'), //barisal
    array('name' => 'Barguna Paurashava', 'ward' => 9,'bn_name' => 'বরগুনা পৌরসভা ', 'district_id' => '35'), //barguna
    array('name' => 'Betagi Paurashava', 'ward' => 9,'bn_name' => 'বেতাগী পৌরসভা', 'district_id' => '35'),
    array('name' => 'Patharghata Paurashava', 'ward' => 9,'bn_name' => 'পাথরঘাটা পৌরসভা', 'district_id' => '35'),
    array('name' => 'Bakerganj Paurashava', 'ward' => 9,'bn_name' => 'বাকেরগঞ্জ পৌরসভা', 'district_id' => '33'),

    // array('name' => 'Banari Para Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Gaornadi Paurashava', 'ward' => 9,'bn_name'  => '', 'district_id' => ''),
    // array('name' => 'Mehendiganj Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Muladi Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bhola Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Burhanuddin Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Char Fasson Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Daulat Khan Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Lalmohan Paurashava', 'ward' => 9,'bn_name'  => '', 'district_id' => ''),
    // array('name' => 'Jhalokati Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nalchity Paurashava', 'ward' => 9,'bn_name'  => '', 'district_id' => ''),
    // array('name' => 'Bauphal Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Galachipa Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kala Para Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kuakata Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Patuakhali Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Mathbaria Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Pirojpur Paurashava', 'ward' => 9,'bn_name'  => '', 'district_id' => ''),
    // array('name' => 'Swarupkati Paurashava', 'ward' => 9,'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bandarban Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Lama Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Akhaura Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Brahmanbaria Paurashava', 'ward' => 12, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kasba Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nabinagar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chandpur Paurashava', 'ward' => 15, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Faridganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Hajiganj Paurashava', 'ward' => 12, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kachua Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Matlab Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Senrarchar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Shahrasti Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Banshkhali Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chandanaish Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Barairhat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Mirsharai Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Patiya Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Rangunia Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Raozan Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sandwip Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Satkania Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sitakunda Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Barura Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chandina Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chauddagram Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Comilla Sadar Dakshin Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Daudkandi Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Debidwar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Homna Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Comilla Adarsha Sadar Paurashava', 'ward' => 18, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Laksam Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nangalkot Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chakoria Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Cox’s Bazar Paurashava', 'ward' => 12, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Maheshkhali Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Teknaf Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chhagalnaiya Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Daganbhuiyan Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Feni Paurashava', 'ward' => 18, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Parshuram Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sonagazi Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Khagrachhari Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Matiranga Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ramgarh Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Lakshmipur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Roypur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ramganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ramgati Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Begomganj (Chaumohani )Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chatkhil Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Basurhat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Hatiya Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kabirhat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Senbagh Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sonaimuri Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Noakhali Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Baghaichhari Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Rangamati Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Dhamrai Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Dohar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Savar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bhanga Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Boalmari Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Faridpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nagarkanda Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Gazipur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Tongi Paurashava', 'ward' => 12, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kaliakair Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kaliganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sreepur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Gopalganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kotalipara Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Muksudpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Tungipara Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Dewanganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Islampur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Jamalpur Paurashava', 'ward' => 12, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Madarganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Melandaha Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sarishabari Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bajitpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bhairab Paurashava', 'ward' => 12, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Hossainpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Karimganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Katiadi Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kishoreganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kuliar Char Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Pakundia Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kalkini Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Madaripur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Shib Char Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Manikganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Singair Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Mirkadim Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Munshiganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bhaluka Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Fulbaria Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    array('name' => 'Gaffargaon Paurashava', 'ward' => 9, 'bn_name' => 'গফরগাঁও পৌরসভা', 'district_id' => '62'),
    array('name' => 'Gauripur Paurashava', 'ward' => 9, 'bn_name' => 'গৌরীপুর পৌরসভা', 'district_id' => '62'),
    array('name' => 'Ishwarganj Paurashava', 'ward' => 9, 'bn_name' => 'ঈশ্বরগঞ্জ পৌরসভা', 'district_id' => '62'),
    array('name' => 'Mymensingh Paurashava', 'ward' => 21, 'bn_name' => 'ময়মনসিংহ পৌরসভা', 'district_id' => '62'),
    array('name' => 'Muktagachha Paurashava', 'ward' => 9, 'bn_name' => 'মুক্তাগাছা পৌরসভা', 'district_id' => '62'),
    array('name' => 'Nandail Paurashava', 'ward' => 9, 'bn_name' => 'নান্দাইল পৌরসভা', 'district_id' => '62'),
    array('name' => 'Phulpur Paurashava', 'ward' => 9, 'bn_name' => 'ফুলপুর পৌরসভা', 'district_id' => '62'),
    array('name' => 'Trishal Paurashava', 'ward' => 9, 'bn_name' => 'ত্রিশাল পৌরসভা', 'district_id' => '62'),
    array('name' => 'Sonargaon Paurashava', 'ward' => 9, 'bn_name' => 'সোনারগাঁ পৌরসভা', 'district_id' => '43'),
    array('name' => 'Narayanganj Paurashava', 'ward' => 9, 'bn_name' => 'নারায়ণগঞ্জ পৌরসভা', 'district_id' => '43'),
    array('name' => 'Siddhirganj Paurashava', 'ward' => 9, 'bn_name' => 'সিদ্ধিরগঞ্জ পৌরসভা', 'district_id' => '43'),
    array('name' => 'Kadam Rasul (Bandar)', 'ward' => 9, 'bn_name' => 'কদম রসুল (বন্দর) পৌরসভা', 'district_id' => '43'),
    array('name' => 'Kanchan Paurashava', 'ward' => 9, 'bn_name' => 'কাঞ্চন পৌরসভা', 'district_id' => '43'),
    array('name' => 'Tarabo Paurashava', 'ward' => 9, 'bn_name' => 'তারাব পৌরসভা', 'district_id' => '43'),
    array('name' => 'Manohardi Paurashava', 'ward' => 9, 'bn_name' => 'মনোহরদী পৌরসভা', 'district_id' => '40'),
    array('name' => 'Madhabdi Paurashava', 'ward' => 9, 'bn_name' => 'মাধবদী পৌরসভা', 'district_id' => '40'),
    array('name' => 'Narsingdi Paurashava', 'ward' => 9, 'bn_name' => 'নরসিংদী পৌরসভা', 'district_id' => '40'),
    array('name' => 'Ghorasal Paurashava', 'ward' => 9, 'bn_name' => 'ঘোড়াশাল পৌরসভা', 'district_id' => '40'),
    array('name' => 'Roypura Paurashava', 'ward' => 9, 'bn_name' => 'রায়পুর  পৌরসভা', 'district_id' => '40'),
    array('name' => 'Shibpur Paurashava', 'ward' => 9, 'bn_name' => 'শিবপুর পৌরসভা', 'district_id' => '40'),
    array('name' => 'Durgapur Paurashava', 'ward' => 9, 'bn_name' => 'দূর্গাপুর পৌরসভা', 'district_id' => '64'),
    array('name' => 'Kendua Paurashava', 'ward' => 9, 'bn_name' => 'কেন্দুয়া পৌরসভা', 'district_id' => '64'),
    array('name' => 'Madan Paurashava', 'ward' => 9, 'bn_name' => 'মদন পৌরসভা', 'district_id' => '64'),
    array('name' => 'Mohanganj Paurashava', 'ward' => 9, 'bn_name' => 'মোহনগঞ্জ পৌরসভা', 'district_id' => '64'),
    array('name' => 'Netrokona Paurashava', 'ward' => 9, 'bn_name' => 'নেত্রকোনা পৌরসভা', 'district_id' => '64'),
    array('name' => 'Goalundo Ghat Paurashava', 'ward' => 9, 'bn_name' => 'গোয়ালন্দঘাট পৌরসভা', 'district_id' => '49'),
    array('name' => 'Pangsha Paurashava', 'ward' => 9, 'bn_name' => 'পাংশা পৌরসভা', 'district_id' => '49'),
    array('name' => 'Rajbari Paurashava', 'ward' => 9, 'bn_name' => 'রাজবাড়ী পৌরসভা', 'district_id' => '49'),
    array('name' => 'Bhedarganj Paurashava', 'ward' => 9, 'bn_name' => 'ভেদরগঞ্জ পৌরসভা', 'district_id' => '42'),
    array('name' => 'Damudya Paurashava', 'ward' => 9, 'bn_name' => 'ডামুড্যা পৌরসভা', 'district_id' => '42'),
    array('name' => 'Naria Paurashava', 'ward' => 9, 'bn_name' => 'নড়িয়া পৌরসভা', 'district_id' => '42'),
    array('name' => 'Shariatpur Paurashava', 'ward' => 9, 'bn_name' => 'শরিয়তপুর পৌরসভা', 'district_id' => '42'),
    array('name' => 'Zajira Paurashava', 'ward' => 9, 'bn_name' => 'জাজিরা পৌরসভা', 'district_id' => '42'),
    array('name' => 'Nakla Paurashava', 'ward' => 9, 'bn_name' => 'নকলা পৌরসভা', 'district_id' => '61'),
    array('name' => 'Nalitabari Paurashava', 'ward' => 9, 'bn_name' => 'নালিতাবাড়ী পৌরসভা', 'district_id' => '61'),
    array('name' => 'Sherpur Paurashava', 'ward' => 9, 'bn_name' => 'শেরপুর  পৌরসভা', 'district_id' => '14'),
    array('name' => 'Sreebardi Paurashava', 'ward' => 9, 'bn_name' => 'শ্রীবর্দি পৌরসভা', 'district_id' => '14'),
    array('name' => 'Bhuapur Paurashava', 'ward' => 9, 'bn_name' => 'ভূঞাপুর পৌরসভা', 'district_id' => '44'),
    array('name' => 'Dhanbari Paurashava', 'ward' => 9, 'bn_name' => 'ধনবাড়ী পৌরসভা', 'district_id' => '44'),
    array('name' => 'Ghatail Paurashava', 'ward' => 9, 'bn_name' => 'ঘাটাইল পৌরসভা', 'district_id' => '44'),
    array('name' => 'Gopalpur Paurashava', 'ward' => 9, 'bn_name' => 'গোপালপুর পৌরসভা', 'district_id' => '44'),
    array('name' => 'Kalihati Paurashava', 'ward' => 9, 'bn_name' => 'কালিহাতী পৌরসভা', 'district_id' => '44'),
    array('name' => 'Madhupur Paurashava', 'ward' => 9, 'bn_name' => 'মধুপুর পৌরসভা', 'district_id' => '44'),
    array('name' => 'Mirzapur Paurashava', 'ward' => 9, 'bn_name' => 'মির্জাপুর পৌরসভা', 'district_id' => '44'),
    array('name' => 'Sakhipur Paurashava', 'ward' => 9, 'bn_name' => 'সখিপুর পৌরসভা', 'district_id' => '44'),
    array('name' => 'Tangail Paurashava', 'ward' => 18, 'bn_name' => 'টাঙ্গাইল পৌরসভা', 'district_id' => '44'),
    array('name' => 'Bagerhat Paurashava', 'ward' => 9, 'bn_name' => 'বাগেরহাট  পৌরসভা', 'district_id' => '28'),
    array('name' => 'Mongla Paurashava', 'ward' => 9, 'bn_name' => 'মংলা পৌরসভা', 'district_id' => '28'),
    array('name' => 'Morrelganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => '28'),
    array('name' => 'Alamdanga Paurashava', 'ward' => 9, 'bn_name' => 'আলমডাঙ্গা পৌরসভা', 'district_id' => '24'),
    array('name' => 'Chuadanga Paurashava', 'ward' => 9, 'bn_name' => 'চুয়াডাঙ্গা পৌরসভা', 'district_id' => '24'),
    array('name' => 'Darshana Paurashava', 'ward' => 9, 'bn_name' => 'দর্শনা পৌরসভা', 'district_id' => '24'),
    array('name' => 'Jibannagar Paurashava', 'ward' => 9, 'bn_name' => 'জীবননগর পৌরসভা', 'district_id' => '24'),
    array('name' => 'Noapara Paurashava', 'ward' => 9, 'bn_name' => 'নোয়াপাড়া পৌরসভা', 'district_id' => '20'),
    array('name' => 'Bagherpara Paurashava', 'ward' => 9, 'bn_name' => 'বাঘারপাড়া পৌরসভা', 'district_id' => '20'),
    array('name' => 'Chaugachha Paurashava', 'ward' => 9, 'bn_name' => 'চৌগাছা পৌরসভা', 'district_id' => '20'),
    array('name' => 'Jhikargachha Paurashava', 'ward' => 9, 'bn_name' => 'ঝিকরগাছা পৌরসভা', 'district_id' => '20'),
    array('name' => 'Keshabpur Paurashava', 'ward' => 9, 'bn_name' => 'কেশবপুর পৌরসভা', 'district_id' => '20'),
    array('name' => 'Jessore Paurashava', 'ward' => 9, 'bn_name' => 'যশোর পৌরসভা', 'district_id' => '20'),
    array('name' => 'Manirampur Paurashava', 'ward' => 9, 'bn_name' => 'মণিরামপুর পৌরসভা', 'district_id' => '20'),
    array('name' => 'Benapole Paurashava', 'ward' => 9, 'bn_name' => 'বেনাপোল পৌরসভা', 'district_id' => '20'),
    array('name' => 'Harinakundu Paurashava', 'ward' => 9, 'bn_name' => 'হরিণাকুন্ড পৌরসভা', 'district_id' => '29'),
    array('name' => 'Jhenaidah Paurashava', 'ward' => 9, 'bn_name' => 'ঝিনাইদহ পৌরসভা', 'district_id' => '29'),
    array('name' => 'Kaliganj Paurashava', 'ward' => 9, 'bn_name' => 'কালীগঞ্জ  পৌরসভা', 'district_id' => '29'),
    array('name' => 'Kotchandpur Paurashava', 'ward' => 9, 'bn_name' => 'কোটচাঁদপুর পৌরসভা', 'district_id' => '29'),
    array('name' => 'Maheshpur Paurashava', 'ward' => 9, 'bn_name' => 'মহেশপুর  পৌরসভা', 'district_id' => '29'),
    array('name' => 'Shailkupa Paurashava', 'ward' => 9, 'bn_name' => 'শৈলকুপা পৌরসভা', 'district_id' => '29'),
    array('name' => 'Chalna Paurashava', 'ward' => 9, 'bn_name' => 'চালনা পৌরসভা', 'district_id' => '27'),
    array('name' => 'Paikgachha Paurashava', 'ward' => 9, 'bn_name' => 'পাইকগাছা পৌরসভা', 'district_id' => '27'),
    array('name' => 'Bheramara Paurashava', 'ward' => 9, 'bn_name' => 'ভেড়ামারা পৌরসভা', 'district_id' => '25'),
    array('name' => 'Khoksa Paurashava', 'ward' => 9, 'bn_name' => 'খোকসা পৌরসভা', 'district_id' => '25'),
    array('name' => 'Kumarkhali Paurashava', 'ward' => 9, 'bn_name' => 'কুমারখালি পৌরসভা', 'district_id' => '25'),
    array('name' => 'Kushtia Paurashava', 'ward' => 12, 'bn_name' => 'কুষ্টিয়া  পৌরসভা', 'district_id' => '25'),
    array('name' => 'Mirpur Paurashava', 'ward' => 9, 'bn_name' => 'মিরপুর পৌরসভা', 'district_id' => '25'),
    array('name' => 'Magura Paurashava', 'ward' => 9, 'bn_name' => 'মাগুরা পৌরসভা', 'district_id' => '26'),
    array('name' => 'Gangni Paurashava', 'ward' => 9, 'bn_name' => 'গাংনী পৌরসভা', 'district_id' => '22'),
    array('name' => 'Meherpur Paurashava', 'ward' => 9, 'bn_name' => 'মেহেরপুর পৌরসভা', 'district_id' => '22'),
    array('name' => 'Kalia Paurashava', 'ward' => 9, 'bn_name' => 'কালিয়া পৌরসভা', 'district_id' => '23'),
    array('name' => 'Lohagara Paurashava', 'ward' => 9, 'bn_name' => 'লোহাগড়া পৌরসভা', 'district_id' => '23'),
    array('name' => 'Narail Paurashava', 'ward' => 9, 'bn_name' => 'নড়াইল  পৌরসভা', 'district_id' => '23'),
    array('name' => 'Kalaroa Paurashava', 'ward' => 9, 'bn_name' => 'কলারোয়া পৌরসভা', 'district_id' => '21'),
    array('name' => 'Satkhira Paurashava', 'ward' => 9, 'bn_name' => 'সাতক্ষীরা  পৌরসভা', 'district_id' => '21'),
    array('name' => 'Santahar Paurashava', 'ward' => 9, 'bn_name' => 'সান্তাহার পৌরসভা', 'district_id' => '14'),
    array('name' => 'Bogra Paurashava', 'ward' => 21, 'bn_name' => 'বগুড়া পৌরসভা', 'district_id' => '14'),
    array('name' => 'Dhunat Paurashava', 'ward' => 9, 'bn_name' => 'ধুনট  পৌরসভা', 'district_id' => '14'),
    array('name' => 'Dhupchanchia Paurashava', 'ward' => 9, 'bn_name' => 'দুপচাঁচিয়া  পৌরসভা', 'district_id' => '14'),
    array('name' => 'Gabtali Paurashava', 'ward' => 9, 'bn_name' => 'গাবতলী  পৌরসভা', 'district_id' => '14'),
    array('name' => 'Kahaloo Paurashava', 'ward' => 9, 'bn_name' => 'কাহালু  পৌরসভা', 'district_id' => '14'),
    array('name' => 'Nandigram Paurashava', 'ward' => 9, 'bn_name' => 'নন্দীগ্রাম  পৌরসভা', 'district_id' => '14'),
    array('name' => 'Sariakandi Paurashava', 'ward' => 9, 'bn_name' => 'সারিয়াকান্দি  পৌরসভা', 'district_id' => '14'), 
    array('name' => 'Shibganj Paurashava', 'ward' => 9, 'bn_name' => 'শিবগঞ্জ পৌরসভা', 'district_id' => '14'),
    array('name' => 'Sonatola Paurashava', 'ward' => 9, 'bn_name' => 'সোনাতলা  পৌরসভা', 'district_id' => '14'),
    array('name' => 'Akkelpur Paurashava', 'ward' => 9, 'bn_name' => 'আক্কেলপুর পৌরসভা', 'district_id' => '17'),
    array('name' => 'Joypurhat Paurashava', 'ward' => 9, 'bn_name' => 'জয়পুরহাট পৌরসভা', 'district_id' => '17'),
    array('name' => 'Kalai Paurashava', 'ward' => 9, 'bn_name' => 'কালাই পৌরসভা', 'district_id' => '17'),
    array('name' => 'Panchbibi Paurashava', 'ward' => 9, 'bn_name' => 'পাঁচবিবি  পৌরসভা', 'district_id' => '17'),
    array('name' => 'Dhamoirhat Paurashava', 'ward' => 9, 'bn_name' => 'ধামইরহাট পৌরসভা', 'district_id' => '19'),
    array('name' => 'Naogaon Paurashava', 'ward' => 9, 'bn_name' => 'নওগাঁ  পৌরসভা', 'district_id' => '19'),
    array('name' => 'Nozipur Paurashava', 'ward' => 9, 'bn_name' => 'নাযিপুর পৌরসভা', 'district_id' => '19'),
    array('name' => 'Bagatipara Paurashava', 'ward' => 9, 'bn_name' => 'বাগাতিপাড়া পৌরসভা', 'district_id' => '16'),
    array('name' => 'Baraigram Paurashava', 'ward' => 9, 'bn_name' => 'বড়াইগ্রাম পৌরসভা', 'district_id' => '16'),
    array('name' => 'Bonpara  Paurashava', 'ward' => 9, 'bn_name' => 'বনপারা পৌরসভা', 'district_id' => '16'),
    array('name' => 'Gurudaspur Paurashava', 'ward' => 9, 'bn_name' => 'গুরুদাসপুর পৌরসভা', 'district_id' => '16'),
    // array('name' => 'Gopalpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    array('name' => 'Natore Paurashava', 'ward' => 9, 'bn_name' => 'নাটোর পৌরসভা', 'district_id' => '16'),
    array('name' => 'Naldanga Paurashava', 'ward' => 9, 'bn_name' => 'নলডাঙ্গা পৌরসভা', 'district_id' => '16'),
    array('name' => 'Singra Paurashava', 'ward' => 12, 'bn_name' => 'সিংড়া পৌরসভা', 'district_id' => '16'),
    array('name' => 'Rahanpur Paurashava', 'ward' => 9, 'bn_name' => 'রহনপুর পৌরসভা', 'district_id' => '18'),
    array('name' => 'Nachole Paurashava', 'ward' => 9, 'bn_name' => 'নাচোল পৌরসভা', 'district_id' => '18'),
    array('name' => 'Chapai Nawabganj Paurashava', 'ward' => 15, 'bn_name' => 'চাঁপাইনবাবগঞ্জ পৌরসভা', 'district_id' => '18'),
    // array('name' => 'Shibganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    array('name' => 'Atgharia Paurashava', 'ward' => 9, 'bn_name' => 'আটঘোরিয়া  পৌরসভা', 'district_id' => '13'),
    array('name' => 'Bera Paurashava', 'ward' => 9, 'bn_name' => 'বেড়া পৌরসভা', 'district_id' => '13'),
    array('name' => 'Bhangura Paurashava', 'ward' => 9, 'bn_name' => 'ভাঙ্গুড়া পৌরসভা', 'district_id' => '13'),
    array('name' => 'Chatmohar Paurashava', 'ward' => 9, 'bn_name' => 'চাটমোহর পৌরসভা', 'district_id' => '13'),
    array('name' => 'Faridpur Paurashava', 'ward' => 9, 'bn_name' => 'ফরিদপুর  পৌরসভা', 'district_id' => '13'),
    array('name' => 'Ishwardi Paurashava', 'ward' => 9, 'bn_name' => 'ঈশ্বরদী পৌরসভা', 'district_id' => '13'),
    array('name' => 'Pabna Paurashava', 'ward' => 15, 'bn_name' => 'পাবনা পৌরসভা', 'district_id' => '13'),
    array('name' => 'Santhia Paurashava', 'ward' => 9, 'bn_name' => 'সাঁথিয়া পৌরসভা', 'district_id' => '13'),
    array('name' => 'Sujanagar Paurashava', 'ward' => 9, 'bn_name' => 'সুজানগর পৌরসভা', 'district_id' => '13'),
    array('name' => 'Bagha Paurashava', 'ward' => 9, 'bn_name' => 'বাঘা পৌরসভা', 'district_id' => '15'),
    array('name' => 'Arani Paurashava', 'ward' => 9, 'bn_name' => 'আড়ানি পৌরসভা', 'district_id' => '15'),
    array('name' => 'Bhabanigonj Paurashava', 'ward' => 9, 'bn_name' => 'ভবানীগঞ্জ পৌরসভা', 'district_id' => '15'),
    array('name' => 'Tahirpur Paurashava', 'ward' => 9, 'bn_name' => 'তাহেরপুর  পৌরসভা', 'district_id' => '15'),
    array('name' => 'Charghat Paurashava', 'ward' => 9, 'bn_name' => 'চারঘাট  পৌরসভা', 'district_id' => '15'),
    array('name' => 'Durgapur Paurashava', 'ward' => 9, 'bn_name' => 'দুর্গাপুর পৌরসভা', 'district_id' => '15'),
    array('name' => 'Godagari Paurashava', 'ward' => 9, 'bn_name' => 'গোদাগাড়ী পৌরসভা', 'district_id' => '15'),
    array('name' => 'Kakonhat Paurashava', 'ward' => 9, 'bn_name' => 'কাঁকনহাট পৌরসভা', 'district_id' => '15'),
    array('name' => 'Kesharhat Paurashava', 'ward' => 9, 'bn_name' => 'কেশরহাট পৌরসভা', 'district_id' => '15'),
    array('name' => 'Katakhali Paurashava', 'ward' => 9, 'bn_name' => 'কাটাখালী পৌরসভা', 'district_id' => '15'),
    array('name' => 'Noahata Paurashava', 'ward' => 9, 'bn_name' => 'নওহাটা পৌরসভা', 'district_id' => '15'),
    array('name' => 'Puthia Paurashava', 'ward' => 9, 'bn_name' => 'পুঠিয়া পৌরসভা', 'district_id' => '15'),
    array('name' => 'Tanore Paurashava', 'ward' => 9, 'bn_name' => 'তানোর পৌরসভা', 'district_id' => '15'),
    array('name' => 'Mundumala Paurashava', 'ward' => 9, 'bn_name' => 'মুন্ডুমালা পৌরসভা', 'district_id' => '15'),
    array('name' => 'Belkuchi Paurashava', 'ward' => 9, 'bn_name' => 'বেলকুচি পৌরসভা', 'district_id' => '12'),
    array('name' => 'Kazipur Paurashava', 'ward' => 9, 'bn_name' => 'কাজীপুর পৌরসভা', 'district_id' => '12'),
    array('name' => 'Royganj Paurashava', 'ward' => 9, 'bn_name' => 'রায়গঞ্জ পৌরসভা', 'district_id' => '12'),
    array('name' => 'Shahjadpur Paurashava', 'ward' => 9, 'bn_name' => 'শাহজাদপুর পৌরসভা', 'district_id' => '12'),
    array('name' => 'Sirajganj Paurashava', 'ward' => 15, 'bn_name' => 'সিরাজগঞ্জ পৌরসভা', 'district_id' => '12'),
    array('name' => 'Ullah Para Paurashava', 'ward' => 9, 'bn_name' => 'উল্লাপাড়া পৌরসভা', 'district_id' => '12'),
    array('name' => 'Birampur Paurashava', 'ward' => 9, 'bn_name' => 'বিরামপুর পৌরসভা', 'district_id' => '54'),
    array('name' => 'Birganj Paurashava', 'ward' => 9, 'bn_name' => 'বীরগঞ্জ পৌরসভা', 'district_id' => '54'),
    array('name' => 'Setabganj Paurashava', 'ward' => 9, 'bn_name' => 'সেতাবগঞ্জ পৌরসভা', 'district_id' => '54'),
    array('name' => 'Fulbari Paurashava', 'ward' => 9, 'bn_name' => 'ফুলবাড়ী পৌরসভা', 'district_id' => '54'),
    array('name' => 'Ghoraghat Paurashava', 'ward' => 9, 'bn_name' => 'ঘোড়াঘাট পৌরসভা', 'district_id' => '54'),
    array('name' => 'Hakimpur Paurashava', 'ward' => 9, 'bn_name' => 'হাকিমপুর পৌরসভা', 'district_id' => '54'),
    array('name' => 'Dinajpur Paurashava', 'ward' => 12, 'bn_name' => 'দিনাজপুর পৌরসভা', 'district_id' => '54'),
    array('name' => 'Parbatipur Paurashava', 'ward' => 9, 'bn_name' => 'পার্বতীপুর পৌরসভা', 'district_id' => '54'),
    array('name' => 'Gaibandha Paurashava', 'ward' => 9, 'bn_name' => 'গাইবান্ধা পৌরসভা', 'district_id' => '57'),
    array('name' => 'Gobindaganj Paurashava', 'ward' => 9, 'bn_name' => 'গোবিন্দগঞ্জ পৌরসভা', 'district_id' => '57'),
    array('name' => 'Sundarganj Paurashava', 'ward' => 9, 'bn_name' => 'সুন্দরগঞ্জ পৌরসভা', 'district_id' => '57'),
    array('name' => 'Kurigram Paurashava', 'ward' => 9, 'bn_name' => 'কুড়িগ্রাম পৌরসভা', 'district_id' => '60'),
    array('name' => 'Nageshwari Paurashava', 'ward' => 9, 'bn_name' => 'নাগেশ্বরী পৌরসভা', 'district_id' => '60'),
    array('name' => 'Ulipur Paurashava', 'ward' => 9, 'bn_name' => 'উলিপুর পৌরসভা', 'district_id' => '60'),
    array('name' => 'Lalmonirhat Paurashava', 'ward' => 9, 'bn_name' => 'লালমনিরহাট পৌরসভা', 'district_id' => '55'),
    array('name' => 'Patgram Paurashava', 'ward' => 9, 'bn_name' => 'পাটগ্রাম পৌরসভা', 'district_id' => '55'),
    array('name' => 'Domar Paurashava', 'ward' => 9, 'bn_name' => 'ডোমার পৌরসভা', 'district_id' => '56'),
    array('name' => 'Jaldhaka Paurashava', 'ward' => 9, 'bn_name' => 'জলঢাকা পৌরসভা', 'district_id' => '56'),
    array('name' => 'Nilphamari Paurashava', 'ward' => 9, 'bn_name' => 'নীলফামারী পৌরসভা', 'district_id' => '56'),
    array('name' => 'Saidpur Paurashava', 'ward' => 9, 'bn_name' => 'bn:সৈয়দপুর  পৌরসভা', 'district_id' => '56'),
    array('name' => 'Boda Paurashava', 'ward' => 9, 'bn_name' => 'বোদা পৌরসভা', 'district_id' => '53'),
    // array('name' => 'Panchagarh Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Badarganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Haragachh Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Rangpur Paurashava', 'ward' => 15, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Pirganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ranisankail Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Thakurgaon Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ajmiriganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chunarughat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Habiganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Shaysestagagj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Madhabpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nabiganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Barlekha Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kamalganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kulaura Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Maulvibazar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sreemangal Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chhatak Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Derai Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Jagannathpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sunamganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Beani Bazar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Golapganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kanaighat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Zakiganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),

);