<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.8.5
 */

/**
 * Database `bd_geo_code`
 */

/* `bd_geo_code`.`Municipals` */
$municipals = array(

    array('name' => 'Barisal City Corporation', 'ward'=> 30, 'bn_name' => 'বরিশাল সিটি কর্পোরেশন' , 'district_id' => '33'),
    array('name' => 'Chattogram City Corporatio', 'ward'=> 41, 'bn_name' => 'চট্টগ্রাম সিটি কর্পোরেশন' , 'district_id' => '8'),
    array('name' => 'Dhaka North City Corporation', 'ward'=> 54, 'bn_name' => 'ঢাকা উত্তর সিটি কর্পোরেশন' , 'district_id' => '47'),
    array('name' => 'Dhaka South City Corporation', 'ward'=> 75, 'bn_name' => 'ঢাকা দক্ষিণ সিটি কর্পোরেশন' , 'district_id' => '47'),
    array('name' => 'Khulna City Corporation', 'ward'=> 31, 'bn_name' => 'খুলনা সিটি কর্পোরেশন' , 'district_id' => '27'),
    array('name' => 'Rajshahi City Corporation', 'ward'=> 30, 'bn_name' => 'রাজশাহী সিটি কর্পোরেশন' , 'district_id' => '15'),
    array('name' => 'Sylhet City corporation', 'ward'=> 27, 'bn_name' => 'সিলেট সিটি কর্পোরেশন' , 'district_id' => '36'),
    array('name' => 'Comilla City Corporation', 'ward'=> 27, 'bn_name' => 'কুমিল্লা সিটি কর্পোরেশন' , 'district_id' => '1'),
    array('name' => 'Gazipur City Corporation', 'ward'=> 57, 'bn_name' => 'গাজীপুর সিটি কর্পোরেশন ' , 'district_id' => '41'),
    array('name' => 'Narayanganj City Corporation', 'ward'=> 27, 'bn_name' => 'নারায়ণগঞ্জ সিটি কর্পোরেশন' , 'district_id' => '43'),
    array('name' => 'Mymensingh City Corporation', 'ward'=> 33, 'bn_name' => 'ময়মনসিংহ সিটি কর্পোরেশন' , 'district_id' => '62'),
    

    array('name' => 'Amtali Paurashava','ward' => 9,'bn_name' => 'আমতলী', 'district_id' => '33'), //barisal
    array('name' => 'Barguna Paurashava', 'ward' => 9,'bn_name' => 'বরগুনা পৌরসভা ', 'district_id' => '35'), //barguna
    array('name' => 'Betagi Paurashava', 'ward' => 9,'bn_name' => 'বেতাগী পৌরসভা', 'district_id' => '35'),
    array('name' => 'Patharghata Paurashava', 'ward' => 9,'bn_name' => 'পাথরঘাটা পৌরসভা', 'district_id' => '35'),
    array('name' => 'Bakerganj Paurashava', 'ward' => 9,'bn_name' => 'বাকেরগঞ্জ পৌরসভা', 'district_id' => '33'),

    // array('name' => 'Banaripara Paurashava', 'ward' => 9,'bn_name' => ' বানারিপাড়া পৌরসভা', 'district_id' => '33'),
    // array('name' => 'Gournadi Paurashava', 'ward' => 9,'bn_name'  => ' গৌরনদী পৌরসভা', 'district_id' => '33'),
    // array('name' => 'Mehendiganj Paurashava', 'ward' => 9,'bn_name' => 'মেহেন্দিগঞ্জ  পৌরসভা', 'district_id' => '33'),
    // array('name' => 'Muladi Paurashava', 'ward' => 9,'bn_name' => 'মুলাদি পৌরসভা', 'district_id' => '33'),
    // array('name' => 'Bhola Paurashava', 'ward' => 9,'bn_name' => 'ভোলা পৌরসভা', 'district_id' => ''),
    // array('name' => 'Burhanuddin Paurashava', 'ward' => 9,'bn_name' => 'বোরহানউদ্দিন পৌরসভা', 'district_id' => '34'),
    // array('name' => 'Char Fasson Paurashava', 'ward' => 9,'bn_name' => 'চর ফ্যাশন পৌরসভা', 'district_id' => '34'),
    // array('name' => 'Daulat Khan Paurashava', 'ward' => 9,'bn_name' => 'দৌলতখান পৌরসভা', 'district_id' => '34'),
    // array('name' => 'Lalmohan Paurashava', 'ward' => 9,'bn_name'  => 'লালমোহন পৌরসভা', 'district_id' => '34'),
    // array('name' => 'Jhalokati Paurashava', 'ward' => 9,'bn_name' => 'ঝালকাঠি পৌরসভা ', 'district_id' => '30'),
    // array('name' => 'Nalchity Paurashava', 'ward' => 9,'bn_name'  => 'নলছিটি', 'district_id' => '30'),
    // array('name' => 'Bauphal Paurashava', 'ward' => 9,'bn_name' => 'বাউফল পৌরসভা', 'district_id' => '31'),
    // array('name' => 'Galachipa Paurashava', 'ward' => 9,'bn_name' => 'গলাচিপা পৌরসভা', 'district_id' => '31'),
    // array('name' => 'Kalapara Paurashava', 'ward' => 9,'bn_name' => 'কলাপাড়া পৌরসভা', 'district_id' => '31'),
    // array('name' => 'Kuakata Paurashava', 'ward' => 9,'bn_name' => 'কুয়াকাটা পৌরসভা', 'district_id' => '31'),
    // array('name' => 'Patuakhali Paurashava', 'ward' => 9,'bn_name' => 'পটুয়াখালী পৌরসভা', 'district_id' => '31'),
    // array('name' => 'Mathbaria Paurashava', 'ward' => 9,'bn_name' => 'মঠবাড়িয়া পৌরসভা', 'district_id' => '32'),
    // array('name' => 'Pirojpur Paurashava', 'ward' => 9,'bn_name'  => 'পিরোজপুর পৌরসভা', 'district_id' => '32'),
    // array('name' => 'Swarupkati Paurashava', 'ward' => 9,'bn_name' => 'স্বরূপকাঠি পৌরসভা', 'district_id' => '32'),
    // array('name' => 'Bandarban Paurashava', 'ward' => 9, 'bn_name' => 'বান্দরবান পৌরসভা', 'district_id' => '11'),
    // array('name' => 'Lama Paurashava', 'ward' => 9, 'bn_name' => 'লামা পৌরসভা', 'district_id' => '11'),
    // array('name' => 'Akhaura Paurashava', 'ward' => 9, 'bn_name' => 'আখাউড়া পৌরসভা', 'district_id' => '3'),
    // array('name' => 'Brahmanbaria Paurashava', 'ward' => 12, 'bn_name' => 'ব্রাহ্মণবাড়িয়া পৌরসভা', 'district_id' => '3'),
    // array('name' => 'Kasba Paurashava', 'ward' => 9, 'bn_name' => 'কসবা পৌরসভা', 'district_id' => '3'),
    // array('name' => 'Nabinagar Paurashava', 'ward' => 9, 'bn_name' => 'নবীনগর পৌরসভা', 'district_id' => '3'),
    // array('name' => 'Chandpur Paurashava', 'ward' => 15, 'bn_name' => 'চাঁদপুর পৌরসভা', 'district_id' => '6'),
    // array('name' => 'Faridganj Paurashava', 'ward' => 9, 'bn_name' => 'ফরিদগঞ্জ পৌরসভা', 'district_id' => '6'),
    // array('name' => 'Hajiganj Paurashava', 'ward' => 12, 'bn_name' => 'হাজীগঞ্জ পৌরসভা', 'district_id' => '6'),
    // array('name' => 'Kachua Paurashava', 'ward' => 9, 'bn_name' => 'কচুয়া পৌরসভা', 'district_id' => '28'),
    // array('name' => 'Matlab Paurashava', 'ward' => 9, 'bn_name' => 'মতলব পৌরসভা', 'district_id' => '6'),
    // array('name' => 'Sonar Char Paurashava', 'ward' => 9, 'bn_name' => 'সোনারচর পৌরসভা', 'district_id' => '31'),
    // array('name' => 'Shahrasti Paurashava', 'ward' => 9, 'bn_name' => 'শাহরাস্তি পৌরসভা', 'district_id' => '6'),
    // array('name' => 'Banshkhali Paurashava', 'ward' => 9, 'bn_name' => 'বাঁশখালী পৌরসভা', 'district_id' => '8'),
    // array('name' => 'Chandanaish Paurashava', 'ward' => 9, 'bn_name' => 'চন্দনাইশ পৌরসভা', 'district_id' => '8'),
    array('name' => 'Barairhat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Mirsarai Paurashava', 'ward' => 9, 'bn_name' => 'মীরসরাই পৌরসভা', 'district_id' => '8'),
    // array('name' => 'Patiya Paurashava', 'ward' => 9, 'bn_name' => 'পটিয়া পৌরসভা', 'district_id' => '8'),
    // array('name' => 'Rangunia Paurashava', 'ward' => 9, 'bn_name' => 'রাঙ্গুনিয়া পৌরসভা', 'district_id' => '8'),
    // array('name' => 'Raozan Paurashava', 'ward' => 9, 'bn_name' => ' রাউজান পৌরসভা', 'district_id' => '8'),
    // array('name' => 'Sandwip Paurashava', 'ward' => 9, 'bn_name' => 'সন্দ্বীপ পৌরসভা', 'district_id' => '8'),
    // array('name' => 'Satkania Paurashava', 'ward' => 9, 'bn_name' => 'সাতকানিয়া পৌরসভা', 'district_id' => '8'),
    // array('name' => 'Sitakunda Paurashava', 'ward' => 9, 'bn_name' => 'সীতাকুণ্ড পৌরসভা', 'district_id' => '8'),
    // array('name' => 'Barura Paurashava', 'ward' => 9, 'bn_name' => 'বরুড়া পৌরসভা', 'district_id' => '1'),
    // array('name' => 'Chandina Paurashava', 'ward' => 9, 'bn_name' => 'চান্দিনা পৌরসভা', 'district_id' => '1'),
    // array('name' => 'Chauddagram Paurashava', 'ward' => 9, 'bn_name' => 'চৌদ্দগ্রাম পৌরসভা', 'district_id' => '1'),
    // array('name' => 'Comilla Sadar Dakshin Paurashava', 'ward' => 9, 'bn_name' => 'কুমিল্লা পৌরসভা', 'district_id' => '1'),
    // array('name' => 'Daudkandi Paurashava', 'ward' => 9, 'bn_name' => 'দাউদকান্দি পৌরসভা', 'district_id' => '1'),
    // array('name' => 'Debidwar Paurashava', 'ward' => 9, 'bn_name' => 'দেবিদ্বার পৌরসভা', 'district_id' => '1'),
    // array('name' => 'Homna Paurashava', 'ward' => 9, 'bn_name' => 'হোমনা পৌরসভা', 'district_id' => '1'),
    // array('name' => 'Comilla Adarsha Sadar Paurashava', 'ward' => 18, 'bn_name' => 'কুমিল্লা আদর্শ সদর পৌরসভা', 'district_id' => ''),
    // array('name' => 'Laksam Paurashava', 'ward' => 9, 'bn_name' => 'লাকসাম পৌরসভা', 'district_id' => '1'),
    // array('name' => 'Nangalkot Paurashava', 'ward' => 9, 'bn_name' => 'নাঙ্গলকোট পৌরসভা', 'district_id' => '1'),
    // array('name' => 'Chakaria Paurashava', 'ward' => 9, 'bn_name' => 'চকরিয়া পৌরসভা', 'district_id' => '9'),
    // array('name' => 'Cox’s Bazar Paurashava', 'ward' => 12, 'bn_name' => 'কক্সবাজার পৌরসভা', 'district_id' => '9'),
    // array('name' => 'Maheshkhali Paurashava', 'ward' => 9, 'bn_name' => 'মহেশখালী পৌরসভা', 'district_id' => '9'),
    // array('name' => 'Teknaf Paurashava', 'ward' => 9, 'bn_name' => 'টেকনাফ পৌরসভা', 'district_id' => '9'),
    // array('name' => 'Chhagalnaiya Paurashava', 'ward' => 9, 'bn_name' => 'ছাগলনাইয়া পৌরসভা', 'district_id' => '2'),
    // array('name' => 'Daganbhuiyan Paurashava', 'ward' => 9, 'bn_name' => 'দাগনভূইয়া পৌরসভা', 'district_id' => '2'),
    // array('name' => 'Feni Paurashava', 'ward' => 18, 'bn_name' => 'ফেনী পৌরসভা', 'district_id' => '2'),
    // array('name' => 'Parshuram Paurashava', 'ward' => 9, 'bn_name' => 'পরশুরাম পৌরসভা', 'district_id' => '2'),
    // array('name' => 'Sonagazi Paurashava', 'ward' => 9, 'bn_name' => 'সোনাগাজী পৌরসভা', 'district_id' => '2'),
    // array('name' => 'Khagrachhari Paurashava', 'ward' => 9, 'bn_name' => 'খাগড়াছড়ি পৌরসভা', 'district_id' => '10'),
    // array('name' => 'Matiranga Paurashava', 'ward' => 9, 'bn_name' => 'মাটিরাঙ্গা পৌরসভা', 'district_id' => '10'),
    // array('name' => 'Ramgarh Paurashava', 'ward' => 9, 'bn_name' => 'রামগড় পৌরসভা', 'district_id' => '10'),
    // array('name' => 'Lakshmipur Paurashava', 'ward' => 9, 'bn_name' => 'লক্ষ্মীপুর পৌরসভা', 'district_id' => '7'),
    // array('name' => 'Roypur Paurashava', 'ward' => 9, 'bn_name' => 'রায়পুর পৌরসভা', 'district_id' => '7'),
    // array('name' => 'Ramganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => '7'),
    // array('name' => 'Ramgati Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Begumganj (Chowmuhani ) Paurashava', 'ward' => 9, 'bn_name' => 'বেগমগঞ্জ (চৌমুহনী) পৌরসভা', 'district_id' => '5'),
    // array('name' => 'Chatkhil Paurashava', 'ward' => 9, 'bn_name' => 'চাটখিল পৌরসভা', 'district_id' => '5'),
    // array('name' => 'Basurhat Paurashava', 'ward' => 9, 'bn_name' => 'বসুরহাট পৌরসভা', 'district_id' => '5'),
    // array('name' => 'Hatiya Paurashava', 'ward' => 9, 'bn_name' => 'হাতিয়া পৌরসভা', 'district_id' => '5'),
    // array('name' => 'Kabirhat Paurashava', 'ward' => 9, 'bn_name' => 'কবিরহাট পৌরসভা', 'district_id' => '5'),
    // array('name' => 'Senbagh Paurashava', 'ward' => 9, 'bn_name' => 'সেনবাগ পৌরসভা', 'district_id' => '5'),
    // array('name' => 'Sonaimuri Paurashava', 'ward' => 9, 'bn_name' => 'সোনাইমুড়ী পৌরসভা', 'district_id' => '5'),
    // array('name' => 'Noakhali Paurashava', 'ward' => 9, 'bn_name' => 'নোয়াখালি  পৌরসভা', 'district_id' => '5'),
    // array('name' => 'Baghaichhari Paurashava', 'ward' => 9, 'bn_name' => 'বাঘাইছড়ি পৌরসভা', 'district_id' => '4'),
    // array('name' => 'Rangamati Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Dhamrai Paurashava', 'ward' => 9, 'bn_name' => 'ধামরাই পৌরসভা', 'district_id' => '47'),
    // array('name' => 'Dohar Paurashava', 'ward' => 9, 'bn_name' => 'দোহার পৌরসভা', 'district_id' => '47'),
    // array('name' => 'Savar Paurashava', 'ward' => 9, 'bn_name' => 'সাভার পৌরসভা', 'district_id' => '47'),
    // array('name' => 'Bhanga Paurashava', 'ward' => 9, 'bn_name' => 'ভাঙ্গা পৌরসভা', 'district_id' => '52'),
    // array('name' => 'Boalmari Paurashava', 'ward' => 9, 'bn_name' => 'বোয়ালমারী পৌরসভা', 'district_id' => '52'),
    // array('name' => 'Faridpur Paurashava', 'ward' => 9, 'bn_name' => 'ফরিদপুর পৌরসভা', 'district_id' => '52'),
    // array('name' => 'Nagarkanda Paurashava', 'ward' => 9, 'bn_name' => 'নগরকান্দা পৌরসভা', 'district_id' => '52'),
    // array('name' => 'Gazipur Paurashava', 'ward' => 9, 'bn_name' => 'গাজীপুর পৌরসভা', 'district_id' => '41'),
    // array('name' => 'Tongi Paurashava', 'ward' => 12, 'bn_name' => 'টঙ্গী পৌরসভা', 'district_id' => '41'),
    // array('name' => 'Kaliakair Paurashava', 'ward' => 9, 'bn_name' => 'কালিয়াকৈর পৌরসভা', 'district_id' => '41'),
    // array('name' => 'Kaliganj Paurashava', 'ward' => 9, 'bn_name' => 'কালীগঞ্জ পৌরসভা', 'district_id' => '29'),
    // array('name' => 'Sreepur Paurashava', 'ward' => 9, 'bn_name' => 'শ্রীপুর পৌরসভা', 'district_id' => '41'),
    // array('name' => 'Gopalganj Paurashava', 'ward' => 9, 'bn_name' => 'গোপালগঞ্জ পৌরসভা', 'district_id' => '51'),
    // array('name' => 'Kotalipara Paurashava', 'ward' => 9, 'bn_name' => 'কোটালীপাড়া পৌরসভা', 'district_id' => '51'),
    // array('name' => 'Muksudpur Paurashava', 'ward' => 9, 'bn_name' => 'মুকসুদপুর পৌরসভা', 'district_id' => '51'),
    // array('name' => 'Tungipara Paurashava', 'ward' => 9, 'bn_name' => 'টুংগীপাড়া পৌরসভা', 'district_id' => '51'),
    // array('name' => 'Dewanganj Paurashava', 'ward' => 9, 'bn_name' => 'দেওয়ানগঞ্জ পৌরসভা', 'district_id' => '63'),
    // array('name' => 'Islampur Paurashava', 'ward' => 9, 'bn_name' => 'ইসলামপুর পৌরসভা', 'district_id' => '63'),
    // array('name' => 'Jamalpur Paurashava', 'ward' => 12, 'bn_name' => 'জামালপুর পৌরসভা', 'district_id' => '63'),
    // array('name' => 'Madarganj Paurashava', 'ward' => 9, 'bn_name' => 'মাদারগঞ্জ পৌরসভা', 'district_id' => '63'),
    // array('name' => 'Melandaha Paurashava', 'ward' => 9, 'bn_name' => 'মেলান্দহ পৌরসভা', 'district_id' => '63'),
    // array('name' => 'Sarishabari Paurashava', 'ward' => 9, 'bn_name' => 'সরিষাবাড়ী পৌরসভা', 'district_id' => '63'),
    // array('name' => 'Bajitpur Paurashava', 'ward' => 9, 'bn_name' => 'বাজিতপুর পৌরসভা', 'district_id' => '45'),
    // array('name' => 'Bhairab Paurashava', 'ward' => 12, 'bn_name' => 'ভৈরব পৌরসভা', 'district_id' => '45'),
    // array('name' => 'Hossainpur Paurashava', 'ward' => 9, 'bn_name' => 'হোসেনপুর পৌরসভা', 'district_id' => '45'),
    array('name' => 'Karimganj Paurashava', 'ward' => 9, 'bn_name' => 'করিমগঞ্জ পৌরসভা', 'district_id' => '45'),
    array('name' => 'Katiadi Paurashava', 'ward' => 9, 'bn_name' => 'কটিয়াদি পৌরসভা', 'district_id' => '45'),
    array('name' => 'Kishoreganj Paurashava', 'ward' => 9, 'bn_name' => 'কিশোরগঞ্জ পৌরসভা', 'district_id' => '45'),
    array('name' => 'Kuliarchar Paurashava', 'ward' => 9, 'bn_name' => 'কুলিয়ারচর পৌরসভা', 'district_id' => '45'),
    array('name' => 'Pakundia Paurashava', 'ward' => 9, 'bn_name' => 'পাকুন্দিয়া পৌরসভা', 'district_id' => '45'),
    array('name' => 'Kalkini Paurashava', 'ward' => 9, 'bn_name' => 'কালকিনি পৌরসভা', 'district_id' => '50'),
    array('name' => 'Madaripur Paurashava', 'ward' => 9, 'bn_name' => 'মাদারিপুর পৌরসভা', 'district_id' => '50'),
    array('name' => 'Shibchar Paurashava', 'ward' => 9, 'bn_name' => 'শিবচর পৌরসভা', 'district_id' => '50'),
    array('name' => 'Manikganj Paurashava', 'ward' => 9, 'bn_name' => 'মানিকগঞ্জ পৌরসভা', 'district_id' => '46'),
    array('name' => 'Singair Paurashava', 'ward' => 9, 'bn_name' => 'সিঙ্গাইর পৌরসভা', 'district_id' => '46'),
    array('name' => 'Mirkadim Paurashava', 'ward' => 9, 'bn_name' => 'মিরকাদিম পৌরসভা', 'district_id' => '48'),
    array('name' => 'Munshiganj Paurashava', 'ward' => 9, 'bn_name' => 'মুন্সিগঞ্জ পৌরসভা', 'district_id' => '48'),
    array('name' => 'Bhaluka Paurashava', 'ward' => 9, 'bn_name' => 'ভালুকা পৌরসভা', 'district_id' => '62'),
    array('name' => 'Fulbaria Paurashava', 'ward' => 9, 'bn_name' => 'ফুলবাড়ীয়া পৌরসভা', 'district_id' => '62'),
    array('name' => 'Gafargaon  Paurashava', 'ward' => 9, 'bn_name' => 'গফরগাঁও পৌরসভা', 'district_id' => '62'),
    // array('name' => 'Gauripur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ishwarganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Mymensingh Paurashava', 'ward' => 21, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Muktagachha Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nandail Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Phulpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Trishal Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sonargaon Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Narayanganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Siddirganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kadam Rasul (Bandar)', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kanchan Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Tarabo Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Manohardi Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Madhabdi Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Narsingdi Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ghorasal Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Roypura Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Shibpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Durgapur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kendua Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Madan Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Mohanganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Netrokona Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Goalandaghat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Pangsha Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Rajbari Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bhedarganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Damudya Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Naria Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Shariatpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Zanjira Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nakla Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nalitabari Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sherpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sreebardi Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bhuapur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Dhanbari Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ghatail Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Gopalpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kalihati Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Madhupur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Mirzapur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sakhipur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Tangail Paurashava', 'ward' => 18, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bagerhat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Mongla Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Morrelganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Alamdanga Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chuadanga Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Darshana Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Jiban Nagar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Noapara Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bagherpara Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chaugachha Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Jhikargachha Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Keshabpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Jessore Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Manirampur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Benapole Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Harinakundu Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Jhenaidah Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kaliganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kotchandpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Maheshpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Shailkupa Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chalna Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Paikgachha Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bheramara Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Khoksa Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kumarkhali Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kushtia Paurashava', 'ward' => 12, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Mirpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Magura Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Gangni Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Meherpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kalia Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Lohagara Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Narail Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kalaroa Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Satkhira Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Santahar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bogra Paurashava', 'ward' => 21, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Dhunat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Dhupchanchia Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Gabtali Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kahaloo Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nandigram Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sariakandi Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sherpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Shibganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sonatola Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Akkelpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Joypurhat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kalai Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Panchbibi Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Dhamoirhat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Naogaon Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nozipur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bagatipara Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Baraigram Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Banpara Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Gurudaspur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Gopalpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Natore Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Naldanga Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Singra Paurashava', 'ward' => 12, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Rahanpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nachole Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chapai Nawabganj Paurashava', 'ward' => 15, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Shibganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Atgharia Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bera Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bhangura Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chatmohar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Faridpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ishwardi Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Pabna Paurashava', 'ward' => 15, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Santhia Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sujanagar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bagha Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Arani Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Bhabanigonj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Tahirpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Charghat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Durgapur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Godagari Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kakanhat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kesharhat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Katakhali Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Noahata Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Puthia Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Tanore Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Mundumala Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Belkuchi Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kazipur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Royganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Shahjadpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sirajganj Paurashava', 'ward' => 15, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ullah Para Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Birampur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Birganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Setabganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Fulbari Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ghoraghat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Hakimpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Dinajpur Paurashava', 'ward' => 12, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Parbatipur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Gaibandha Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Gobindaganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sundarganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kurigram Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nageshwari Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ulipur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Lalmonirhat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Patgram Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Domar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Jaldhaka Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nilphamari Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Saidpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Boda Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Panchagarh Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Badarganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Haragachh Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Rangpur Paurashava', 'ward' => 15, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Pirganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ranisankail Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Thakurgaon Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Ajmiriganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chunarughat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Habiganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Shaysestagagj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Madhabpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Nabiganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Barlekha Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kamalganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kulaura Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Maulvibazar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sreemangal Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Chhatak Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Derai Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Jagannathpur Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Sunamganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Beani Bazar Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Golapganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Kanaighat Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),
    // array('name' => 'Zakiganj Paurashava', 'ward' => 9, 'bn_name' => ' পৌরসভা', 'district_id' => ''),

);